name: tests

on:
  pull_request:
  push:

jobs:
  nimble-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1
      - run: nimble install -y
      - run: nimble test
      - run: nimble testjs

